version: '3'
services:
  dev:
    image: node:12
    env_file:
      - .env
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=tecpeldb
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=tecpel
      - POSTGRES_PASSWORD=tecpel
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
volumes:
  nodemodules:
    external: true
